/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jspb.exttest.nested.TestNestedExtensionsMessage', null, global);
goog.exportSymbol('proto.jspb.exttest.nested.TestOuterMessage', null, global);
goog.exportSymbol('proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 2, null, null);
};
goog.inherits(proto.jspb.exttest.nested.TestNestedExtensionsMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jspb.exttest.nested.TestNestedExtensionsMessage.displayName = 'proto.jspb.exttest.nested.TestNestedExtensionsMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.jspb.exttest.nested.TestNestedExtensionsMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jspb.exttest.nested.TestNestedExtensionsMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    intfield: jspb.Message.getField(msg, 1)
  };

  jspb.Message.toObjectExtension(/** @type {!jspb.Message} */ (msg), obj,
      proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensions, proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.getExtension,
      includeInstance);
  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jspb.exttest.nested.TestNestedExtensionsMessage}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jspb.exttest.nested.TestNestedExtensionsMessage;
  return proto.jspb.exttest.nested.TestNestedExtensionsMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jspb.exttest.nested.TestNestedExtensionsMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jspb.exttest.nested.TestNestedExtensionsMessage}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntfield(value);
      break;
    default:
      jspb.Message.readBinaryExtension(msg, reader, proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensionsBinary,
        proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.getExtension,
        proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.setExtension);
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jspb.exttest.nested.TestNestedExtensionsMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jspb.exttest.nested.TestNestedExtensionsMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  jspb.Message.serializeBinaryExtensions(message, writer,
    proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensionsBinary, proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.getExtension);
};


/**
 * optional int32 intfield = 1;
 * @return {number}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.getIntfield = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.setIntfield = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.clearIntfield = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.prototype.hasIntfield = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldInfo>}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensions = {};


/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldBinaryInfo>}
 */
proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensionsBinary = {};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jspb.exttest.nested.TestOuterMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jspb.exttest.nested.TestOuterMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jspb.exttest.nested.TestOuterMessage.displayName = 'proto.jspb.exttest.nested.TestOuterMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jspb.exttest.nested.TestOuterMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.jspb.exttest.nested.TestOuterMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jspb.exttest.nested.TestOuterMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestOuterMessage.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jspb.exttest.nested.TestOuterMessage}
 */
proto.jspb.exttest.nested.TestOuterMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jspb.exttest.nested.TestOuterMessage;
  return proto.jspb.exttest.nested.TestOuterMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jspb.exttest.nested.TestOuterMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jspb.exttest.nested.TestOuterMessage}
 */
proto.jspb.exttest.nested.TestOuterMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jspb.exttest.nested.TestOuterMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jspb.exttest.nested.TestOuterMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jspb.exttest.nested.TestOuterMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestOuterMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.displayName = 'proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    ext1: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage;
  return proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExt1(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ext1 = 1;
 * @return {string}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.getExt1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.setExt1 = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.clearExt1 = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.prototype.hasExt1 = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `innerExtension`.
 * @type {!jspb.ExtensionFieldInfo<!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage>}
 */
proto.jspb.exttest.nested.TestOuterMessage.innerExtension = new jspb.ExtensionFieldInfo(
    100,
    {innerExtension: 0},
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.toObject),
    0);

proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensionsBinary[100] = new jspb.ExtensionFieldBinaryInfo(
    proto.jspb.exttest.nested.TestOuterMessage.innerExtension,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.serializeBinaryToWriter,
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensions[100] = proto.jspb.exttest.nested.TestOuterMessage.innerExtension;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `innerExtension`.
 * @type {!jspb.ExtensionFieldInfo<!proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage>}
 */
proto.jspb.exttest.nested.TestOuterMessage.innerExtension = new jspb.ExtensionFieldInfo(
    100,
    {innerExtension: 0},
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.toObject),
    0);

proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensionsBinary[100] = new jspb.ExtensionFieldBinaryInfo(
    proto.jspb.exttest.nested.TestOuterMessage.innerExtension,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.serializeBinaryToWriter,
    proto.jspb.exttest.nested.TestOuterMessage.NestedExtensionMessage.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
proto.jspb.exttest.nested.TestNestedExtensionsMessage.extensions[100] = proto.jspb.exttest.nested.TestOuterMessage.innerExtension;

goog.object.extend(exports, proto.jspb.exttest.nested);
